version: "3.7"

services:
  app:
    image: node:18
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 8081:8081
      - 35729:35729
    command: npm run local:dev
    user: 1000:1000
