export const sec = 1000
export const min = sec * 60
export const hour = min * 60
export const day = hour * 24
export const week = day * 7
export const month = day * 30
export const year = day * 365
export const COVER_EMAIL = 'cover@sil.org'
export const MAX_INPUT_LENGTH = 255
export const MAX_TEXT_AREA_LENGTH = 2048
